services:
  api:
    container_name: rest-app
    build:
      context: .
      target: development
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:4-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Ensures data persistence
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
    restart: unless-stopped
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  rabbitmq_data:
  postgres_data: